### ISSUE TITLE
Integration does not show any picture in Discord

### ISSUE THREAD

**Issue by samip5** [jivandabeast/TraktDiscordRP#2]
Shouldn't it include an icon in the "playing a game" as well?

**Comment by jivandabeast** [comment]
Can you be more specific as to what you mean?

![image](https://user-images.githubusercontent.com/22606920/148454638-742ca798-6a61-49d9-8a6a-6b94b69ef401.png)

This is how it should look, you have to make sure that you've set up the application in discord correctly to have the referenced assets.

**Comment by samip5** [comment]
> Can you be more specific as to what you mean?
> 
> ![image](https://user-images.githubusercontent.com/22606920/148454638-742ca798-6a61-49d9-8a6a-6b94b69ef401.png)
> 
> This is how it should look, you have to make sure that you've set up the application in discord correctly to have the referenced assets.

~~Mine doesn't let me upload the assets to the application under rich presence.~~ Other RPC things usually do it from the RPC itself.
It took a while for it to show up that the assets were in fact uploaded.

![image](https://user-images.githubusercontent.com/1703002/148514352-ed826733-d236-4fd3-b38a-591961db30da.png)
