### ISSUE TITLE
Movies rating

### ISSUE THREAD

**Issue by NanoBitrin** [jivandabeast/TraktDiscordRP#4]
Is it possible instead to have the link to the IMDB page of the movie, can we have the rating of it?
![image](https://user-images.githubusercontent.com/17798233/148686030-cfc2f0e3-c631-4d37-bfde-d7c370586f0f.png)

**Comment by jivandabeast** [comment]
Yeah I'll take a look at this and #3 later today

**Comment by NanoBitrin** [comment]
And the IMDB link, you can create a button using the spectate?
